apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-pv1
  namespace: zookeeper
spec:
  capacity:
    storage: 1Gi  # Match this with the storage requested by the PVC
  accessModes:
    - ReadWriteOnce  # Match this with the access modes required by the PVC
  storageClassName: standard  # Match this with the storage class used by the PVC (if any)
  hostPath:
    path: /mnt/data/zookeeper # Path on the host where the data will be stored
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-pv2
  namespace: zookeeper
spec:
  capacity:
    storage: 1Gi  # Match this with the storage requested by the PVC
  accessModes:
    - ReadWriteOnce  # Match this with the access modes required by the PVC
  storageClassName: standard  # Match this with the storage class used by the PVC (if any)
  hostPath:
    path: /mnt/data/zookeeper # Path on the host where the data will be stored
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-pv3
  namespace: zookeeper
spec:
  capacity:
    storage: 1Gi  # Match this with the storage requested by the PVC
  accessModes:
    - ReadWriteOnce  # Match this with the access modes required by the PVC
  storageClassName: standard  # Match this with the storage class used by the PVC (if any)
  hostPath:
    path: /mnt/data/zookeeper # Path on the host where the data will be stored
