---
- hosts: masters
  become: yes
  tasks:
    - name: Initialize Kubernetes Master
      shell: |
        sudo kubeadm init --pod-network-cidr=10.220.0.0/8

    - name: Create .kube directory
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Copy Kube config to user directory
      command: sudo cp /etc/kubernetes/admin.conf /home/vagrant/.kube/config

    - name: Change ownership to current user
      file:
        path: /home/vagrant/.kube/config
        owner: vagrant
        group: vagrant

    - name: Set KUBECONFIG environment variable
      shell: echo "export KUBECONFIG=/home/vagrant/.kube/config" >> /home/vagrant/.bashrc
      become_user: vagrant

        #- name: Apply Calico network plugin
        #command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
        #environment:
        #KUBECONFIG: /home/vagrant/.kube/config

