apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse-cluster"
  namespace: "clickhouse"
spec:
  configuration:
    users:
      admin/password: "Password.123"
      admin/networks/ip:
        - '0.0.0.0/0'
        - '::/0'
      admin/profile: default
      admin/quota: default
    clusters:
      - name: "cluster1"
        layout:
          shardsCount: 1
          replicasCount: 2
        templates:
          podTemplate: "default"
          dataVolumeClaimTemplate: "storage-template"
    zookeeper:
        nodes:
        - host: zk-hs
          port: 2181
  templates:
    podTemplates:
      - name: "default"
        spec:
          containers:
            - name: "clickhouse"
              image: "clickhouse/clickhouse-server:23.8"
              ports:
                - name: "http"
                  containerPort: 8123
                - name: "tcp"
                  containerPort: 9000
    volumeClaimTemplates:
      - name: "storage-template"
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: longhorn
          resources:
            requests:
              storage: 5Gi
