apiVersion: v1
kind: PersistentVolume
metadata:
  name: ch-pv1
  namespace: clickhouse
spec:
  capacity:
    storage: 10Gi  # Match this with the storage requested by the PVC
  accessModes:
    - ReadWriteOnce  # Match this with the access modes required by the PVC
  storageClassName: standard  # Match this with the storage class used by the PVC (if any)
  hostPath:
    path: /mnt/data/clickhouse-1 # Path on the host where the data will be stored
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ch-pv2
  namespace: clickhouse
spec:
  capacity:
    storage: 10Gi  # Match this with the storage requested by the PVC
  accessModes:
    - ReadWriteOnce  # Match this with the access modes required by the PVC
  storageClassName: standard  # Match this with the storage class used by the PVC (if any)
  hostPath:
    path: /mnt/data/clickhouse-2 # Path on the host where the data will be stored
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ch-pv3
  namespace: clickhouse
spec:
  capacity:
    storage: 10Gi  # Match this with the storage requested by the PVC
  accessModes:
    - ReadWriteOnce  # Match this with the access modes required by the PVC
  storageClassName: standard  # Match this with the storage class used by the PVC (if any)
  hostPath:
    path: /mnt/data/clickhouse-3 # Path on the host where the data will be stored
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ch-pv4
  namespace: clickhouse
spec:
  capacity:
    storage: 10Gi  # Match this with the storage requested by the PVC
  accessModes:
    - ReadWriteOnce  # Match this with the access modes required by the PVC
  storageClassName: standard  # Match this with the storage class used by the PVC (if any)
  hostPath:
    path: /mnt/data/clickhouse-4 # Path on the host where the data will be stored
