apiVersion: v1
kind: Pod
metadata:
  name: clickhouse-client
  namespace: clickhouse
  labels:
    app: clickhouse-client
spec:
  containers:
    - name: clickhouse-client
      image: clickhouse/clickhouse-client:latest
      command: ["/bin/sh", "-c", "sleep 100000"]
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "64Mi"
          cpu: "100m"
      env:
        - name: CLICKHOUSE_HOST
          value: "clickhouse-clickhouse-cluster.clickhouse" # Set your ClickHouse host
        - name: CLICKHOUSE_PORT
          value: "9000" # Default ClickHouse port
        - name: CLICKHOUSE_USER
          value: "admin" # Update username if necessary
        - name: CLICKHOUSE_PASSWORD
          value: "Password.123" # Update with password if necessary

