apiVersion: v1
kind: Pod
metadata:
  name: nats-box
  namespace: nats-ns
  labels:
    app: nats-box
spec:
  containers:
    - name: nats-box
      image: synadia/nats-box:latest
      command: ["/bin/sh", "-c", "sleep 100000"]
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "64Mi"
          cpu: "100m"

