apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: nats-ns
data:
  nats.conf: |
    # NATS Server configuration
    server_name: ${SERVER_NAME}
    listen: 0.0.0.0:4222
    # Enable JetStream
    jetstream: {
      store_dir: "/data/jetstream"
    }
    # Cluster configuration
    cluster {
      name: "nats-cluster"
      listen: 0.0.0.0:6222
      # Routes to connect the NATS nodes
      routes = [
        nats-route://nats-0:6222
        nats-route://nats-1:6222
        nats-route://nats-2:6222
      ]
    }
