apiVersion: v1
kind: Service
metadata:
  name: nats-svc
  namespace: nats-ns
spec:
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: cluster
      port: 6222
      targetPort: 6222
  selector:
    app: nats
