apiVersion: v1
kind: Service
metadata:
  name: nats-np-svc
  namespace: nats-ns
spec:
  type: NodePort
  ports:
    - name: client
      port: 4222
      protocol: TCP
      targetPort: 4222
      nodePort: 30002
    - name: cluster
      port: 6222
      protocol: TCP
      targetPort: 6222
      nodePort: 30003
  selector:
    app: nats
